##  Project Assignment - Specialist Certificate in Data Analytics Essentials- Robbie Pratt (Secondary Dataset)

### 2.1. Your project should make use of the following - Web Scraping

#### 1.1. Import Python Packages

In [22]:
import pandas as pd

URL

In [23]:
url = 'https://autotraveler.ru/en/spravka/fuel-price-in-europe.html#.Y7rDpv7P25c.html'

### Using pd.read_html() function to read HTML webpage

In [24]:
df = pd.read_html(url, header = 0)
df

[    â                 Country         E5 (Super)    E5 (Super Plus)  \
 0     1                 Austria  â¬ 1.49 (+ 0.02)  â¬ 1.69 (+ 0.02)
 1     2              Azerbaijan           â¬ 1.11  â¬ 1.27 (- 0.01)
 2     3                 Albania  â¬ 1.54 (+ 0.01)                NaN
 3     4                 Andorra           â¬ 1.49           â¬ 1.55
 4     5                 Armenia           â¬ 1.07           â¬ 1.15
 5     6                 Belarus  â¬ 0.84 (- 0.06)  â¬ 0.92 (- 0.06)
 6     7                 Belgium  â¬ 1.76 (+ 0.08)  â¬ 1.95 (+ 0.08)
 7     8                Bulgaria  â¬ 1.35 (- 0.02)  â¬ 1.55 (- 0.04)
 8     9  Bosnia and Herzegovina  â¬ 1.42 (- 0.03)           â¬ 1.54
 9    10           Great Britain  â¬ 1.78 (- 0.08)  â¬ 2.26 (- 0.04)
 10   11                 Hungary  â¬ 1.65 (+ 0.07)  â¬ 1.71 (+ 0.04)
 11   12                 Germany  â¬ 1.85 (+ 0.05)           â¬ 1.86
 12   13                  Greece  â¬ 1.86 (+ 0.03)           â¬ 2.06
 13   14                 Georgia  â¬ 1.11 (- 0.04)  â¬ 1.30 (- 0.03)
 14   15                 Denmark  â¬ 1.88 (+ 0.08)  â¬ 2.02 (+ 0.09)
 15   16                 Ireland  â¬ 1.54 (- 0.02)                NaN
 16   17                 Iceland  â¬ 2.02 (+ 0.03)                NaN
 17   18                   Spain  â¬ 1.61 (+ 0.05)  â¬ 1.77 (+ 0.05)
 18   19                   Italy  â¬ 1.83 (+ 0.18)  â¬ 2.02 (+ 0.15)
 19   20                  Cyprus  â¬ 1.39 (- 0.04)  â¬ 1.47 (- 0.03)
 20   21                  Latvia  â¬ 1.62 (+ 0.03)  â¬ 1.66 (+ 0.03)
 21   22               Lithuania           â¬ 1.46  â¬ 1.58 (+ 0.02)
 22   23              Luxembourg  â¬ 1.51 (+ 0.06)  â¬ 1.73 (+ 0.05)
 23   24         North Macedonia  â¬ 1.25 (+ 0.02)  â¬ 1.29 (+ 0.01)
 24   25                   Malta           â¬ 1.34           â¬ 1.49
 25   26                 Moldova  â¬ 1.11 (+ 0.03)  â¬ 1.43 (- 0.07)
 26   27             Netherlands  â¬ 1.96 (+ 0.07)  â¬ 2.09 (+ 0.07)
 27   28                  Norway  â¬ 2.06 (+ 0.15)  â¬ 2.19 (+ 0.15)
 28   29                  Poland           â¬ 1.39           â¬ 1.47
 29   30                Portugal  â¬ 1.73 (+ 0.10)  â¬ 1.90 (+ 0.09)
 30   31                 Romania  â¬ 1.28 (- 0.01)  â¬ 1.37 (- 0.04)
 31   32                  Serbia  â¬ 1.40 (- 0.02)  â¬ 1.56 (- 0.03)
 32   33                Slovakia  â¬ 1.50 (- 0.02)  â¬ 1.68 (- 0.02)
 33   34                Slovenia  â¬ 1.24 (- 0.13)  â¬ 1.49 (- 0.17)
 34   35                  Turkey  â¬ 0.98 (+ 0.08)  â¬ 1.00 (+ 0.08)
 35   36                 Ukraine           â¬ 1.32  â¬ 1.35 (+ 0.01)
 36   37                 Finland  â¬ 1.94 (+ 0.05)  â¬ 2.04 (+ 0.05)
 37   38                  France  â¬ 1.86 (+ 0.19)  â¬ 1.93 (+ 0.20)
 38   39                 Croatia  â¬ 1.33 (+ 0.05)  â¬ 1.64 (+ 0.06)
 39   40              Montenegro           â¬ 1.43           â¬ 1.47
 40   41          Czech Republic  â¬ 1.50 (+ 0.02)  â¬ 1.62 (- 0.01)
 41   42             Switzerland  â¬ 1.82 (+ 0.01)  â¬ 1.94 (+ 0.01)
 42   43                  Sweden           â¬ 1.71  â¬ 1.80 (+ 0.01)
 43   44                 Estonia  â¬ 1.72 (+ 0.02)  â¬ 1.77 (+ 0.02)
 44   45                  Russia           â¬ 0.67  â¬ 0.80 (- 0.01)

             B7 Diesel
 0   â¬ 1.69 (+ 0.02)
 1            â¬ 0.44
 2   â¬ 1.72 (+ 0.01)
 3            â¬ 1.52
 4            â¬ 1.00
 5   â¬ 0.84 (- 0.06)
 6   â¬ 1.82 (+ 0.03)
 7   â¬ 1.55 (- 0.03)
 8   â¬ 1.61 (- 0.04)
 9   â¬ 2.10 (+ 0.03)
 10  â¬ 1.81 (+ 0.03)
 11  â¬ 1.90 (+ 0.02)
 12           â¬ 1.80
 13  â¬ 1.37 (- 0.03)
 14  â¬ 1.85 (+ 0.06)
 15  â¬ 1.63 (- 0.02)
 16  â¬ 2.11 (+ 0.05)
 17  â¬ 1.67 (+ 0.03)
 18  â¬ 1.89 (+ 0.19)
 19  â¬ 1.59 (- 0.07)
 20  â¬ 1.71 (+ 0.06)
 21  â¬ 1.66 (+ 0.04)
 22  â¬ 1.63 (+ 0.03)
 23  â¬ 1.30 (- 0.01)
 24           â¬ 1.21
 25  â¬ 1.13 (+ 0.02)
 26  â¬ 1.92 (+ 0.04)
 27  â¬ 2.07 (+ 0.07)
 28  â¬ 1.63 (- 0.01)
 29  â¬ 1.71 (+ 0.03)
 30  â¬ 1.52 (- 0.01)
 31  â¬ 1.68 (- 0.02)
 32  â¬ 1.62 (- 0.03)
 33  â¬ 1.47 (- 0.09)
 34           â¬ 1.11
 35  â¬ 1.41 (+ 0.01)
 36  â¬ 2.11 (+ 0.10)
 37  â¬ 1.93 (+ 0.17)
 38  â¬ 1.47 (+ 0.03)
 39           â¬ 1.51
 40           â¬ 1.55
 41  â¬ 2.11 (+ 0.01)
 42  â¬ 2.12 (- 0.02)
 43  â¬ 1.75 (+ 0.05)
 44           â¬ 0.75  ,
                    Country            E5 (Super)      E5 (Super Plus)  \
 0                  Austria                   NaN                  NaN
 1               Azerbaijan              AZN 2.00             AZN 2.30
 2                  Albania            ALL 175.00                  NaN
 3                  Andorra                   NaN                  NaN
 4                  Armenia            AMD 450.00           AMD 480.00
 5                  Belarus              BYN 2.46             BYN 2.68
 6                  Belgium                   NaN                  NaN
 7                 Bulgaria     BGN 2.64 (- 0.03)    BGN 3.03 (- 0.07)
 8   Bosnia and Herzegovina     BAM 2.78 (- 0.05)             BAM 3.01
 9            Great Britain     GBP 1.58 (- 0.04)             GBP 2.00
 10                 Hungary  HUF 654.80 (+ 20.10)  HUF 677.90 (+ 7.80)
 11                 Germany                   NaN                  NaN
 12                  Greece                   NaN                  NaN
 13                 Georgia     GEL 3.20 (- 0.05)             GEL 3.75
 14                 Denmark    DKK 13.99 (+ 0.60)   DKK 14.99 (+ 0.61)
 15                 Ireland                   NaN                  NaN
 16                 Iceland   ISK 308.10 (+ 4.24)                  NaN
 17                   Spain                   NaN                  NaN
 18                   Italy                   NaN                  NaN
 19                  Cyprus                   NaN                  NaN
 20                  Latvia                   NaN                  NaN
 21               Lithuania                   NaN                  NaN
 22              Luxembourg                   NaN                  NaN
 23         North Macedonia    MKD 77.00 (+ 1.00)   MKD 79.50 (+ 1.00)
 24                   Malta                   NaN                  NaN
 25                 Moldova    MDL 22.62 (+ 0.49)   MDL 29.35 (- 1.50)
 26             Netherlands                   NaN                  NaN
 27                  Norway    NOK 21.61 (+ 1.59)   NOK 23.01 (+ 1.59)
 28                  Poland     PLN 6.49 (+ 0.02)             PLN 6.85
 29                Portugal                   NaN                  NaN
 30                 Romania     RON 6.29 (- 0.03)    RON 6.75 (- 0.13)
 31                  Serbia   RSD 164.00 (- 3.00)  RSD 183.00 (- 3.00)
 32                Slovakia                   NaN                  NaN
 33                Slovenia                   NaN                  NaN
 34                  Turkey    TRY 19.46 (+ 1.62)   TRY 19.91 (+ 1.62)
 35                 Ukraine    UAH 51.71 (- 0.13)   UAH 52.70 (+ 0.03)
 36                 Finland                   NaN                  NaN
 37                  France                   NaN                  NaN
 38                 Croatia    HRK 10.03 (+ 0.40)   HRK 12.37 (+ 0.44)
 39              Montenegro                   NaN                  NaN
 40          Czech Republic             CZK 35.93   CZK 38.96 (- 0.41)
 41             Switzerland              CHF 1.79             CHF 1.91
 42                  Sweden    SEK 19.10 (+ 0.21)   SEK 20.05 (+ 0.21)
 43                 Estonia                   NaN                  NaN
 44                  Russia             RUB 51.60   RUB 61.98 (+ 0.03)

               B7 Diesel
 0                   NaN
 1              AZN 0.80
 2            ALL 196.00
 3                   NaN
 4            AMD 420.00
 5              BYN 2.46
 6                   NaN
 7     BGN 3.02 (- 0.07)
 8     BAM 3.14 (- 0.09)
 9     GBP 1.86 (+ 0.06)
 10  HUF 717.80 (+ 2.20)
 11                  NaN
 12                  NaN
 13             GEL 3.95
 14   DKK 13.79 (+ 0.50)
 15                  NaN
 16  ISK 320.62 (+ 5.14)
 17                  NaN
 18                  NaN
 19                  NaN
 20                  NaN
 21                  NaN
 22                  NaN
 23   MKD 80.00 (- 0.50)
 24                  NaN
 25   MDL 23.18 (+ 0.32)
 26                  NaN
 27   NOK 21.73 (+ 0.76)
 28    PLN 7.62 (+ 0.01)
 29                  NaN
 30    RON 7.48 (+ 0.01)
 31  RSD 197.00 (- 2.00)
 32                  NaN
 33                  NaN
 34   TRY 22.06 (+ 0.01)
 35   UAH 55.07 (+ 0.04)
 36                  NaN
 37                  NaN
 38   HRK 11.08 (+ 0.24)
 39                  NaN
 40   CZK 37.27 (- 0.14)
 41             CHF 2.08
 42   SEK 23.61 (- 0.06)
 43                  NaN
 44   RUB 57.80 (+ 0.61)  ]